---
directories:
    work_dir: /usr/local/www/data/private/Glycine/liu_et_al_2020_pangenome/max
    from_annot_dir: SoyL08_asm_GWHACEI00000000
    from_genome_dir: SoyL08_asm_GWHACEI00000000
prefixes:
    from_annot_prefix: GWHACEI00000000.
    from_genome_prefix: GWHACEI00000000.
collection_info:
    genus: Glycine
    species: max
    gensp: glyma
    genotype: TieJiaSiLiHuang
    gnm_ver: gnm1
    ann_ver: ann1
    genome_key: W9PV
    annot_key: W70Z
readme_info:
    provenance: "The files in this directory originated from the Genome Warehouse of the China National Center for Bioinformation, https://ngdc.cncb.ac.cn/gwh. The Genome Warehouse repository is considered the primary repository and authoritative; files in this present directory are derived, and may have changes, as noted below. The files here are held as part of the LegumeInfo and SoyBase projects, and are made available here for the purpose of reproducibility of analyses at these sites (e.g. gene family alignments and phylogenies, genome browsers, etc.) and for further use by researchers, as that research extends other analyses at the LegumeInfo and SoyBase projects. If you are conducting research on large-scale data sets for this species, please consider retrieving the data from the primary repositories. If you use the data in the present directory, please respect any usage restrictions in the present and original repositories, and cite the data appropriately."
    source: https://ngdc.cncb.ac.cn/gwh/Genome/43/show
    synopsis_genome: Genome assembly for Glycine max accession TieJiaSiLiHuang (SoyL08) from Liu, Du et al. 2020.
    synopsis_annot: Gene annotations for Glycine max accession TieJiaSiLiHuang (SoyL08) from Liu, Du et al. 2020.
    taxid: 3847
    description_genome: Genome assembly for Glycine max accession TieJiaSiLiHuang (SoyL08) from Liu, Du et al. 2020. The 26 accessions were sequenced individually using single-molecule real-time (SMRT) sequencing with an average coverage depth of 96X, optical mapping with an average coverage depth of 277X, chromosome conformation capture (Hi-C) sequencing with an average coverage depth of 136X, and Illumina sequencing (HiSeq) with an average coverage depth of 68X.
    description_annot: Gene annotations for Glycine max accession TieJiaSiLiHuang (SoyL08) from Liu, Du et al. 2020. Annotations of the protein-coding and small RNA genes employed Augustus trained by FGENESH, transcript support based on RNA samples from roots, stems, leaves, flowers, and seeds at different developmental stages;and integration of ab initio and evidence-based results with MAKER.
    bioproject: 
    sraproject: 
    dataset_doi_genome: 
    dataset_doi_annot: 
    genbank_accession: 
    original_file_creation_date: "2020-04-08"
    local_file_creation_date: "2022-12-09"
    dataset_release_date: "2022-12-12"
    contributors: Yucheng Liu, Huilong Du, Haikuan Zhang, Yanting Shen, Hua Peng, Shulin Liu, Guo-An Zhou, Miao Shi, Pengcheng Li, Xuehui Huang, Yan Li, Min Zhang, Zheng Wang, Baoge Zhu, Bin Han, Chengzhi Liang, Zhixi Tian
    publication_doi: 10.1016/j.cell.2020.05.023
    citation: "Liu Y, Du H, Li P, Shen Y, Peng H, Liu S, Zhou GA, Zhang H, Liu Z, Shi M, Huang X, Li Y, Zhang M, Wang Z, Zhu B, Han B, Liang C, Tian Z. Pan-Genome of Wild and Cultivated Soybeans. Cell. 2020 Jul 9;182(1):162-176.e13. doi: 10.1016/j.cell.2020.05.023. Epub 2020 Jun 17. PMID: 32553274."
    publication_title: "Pan-Genome of Wild and Cultivated Soybeans"
    data_curators: Andrew Farmer, Steven Cannon
    public_access_level: public
    license: open
    keywords: "soybean, pangenome"
from_to_annot_as_is:
  -
    from: feature.gz
    to: feature.tsv
    description: Table of original feature IDs and coordinates
from_to_genome:
  -
    from: genome_modID.fasta.gz
    to: genome_main.fna
    description: Primary genome assembly
from_to_cds_mrna:
  -
    from: CDS.fna.gz
    to: cds.fna
    description: CDS sequences
  -
    from: CDS_primary.fna.gz
    to: cds_primary.fna
    description: CDS sequences - primary only
from_to_protein:
  -
    from: protein.faa.gz
    to: protein.faa
    description: Protein sequences
  -
    from: protein_primary.faa.gz
    to: protein_primary.faa
    description: Protein sequences - primary only
from_to_gff:
  -
    from: modID.gff3.gz
    to: gene_models_main.gff3
    description: Gene models - main
